[project]
timeout = 30

[[tests]]
name = "01"
input = ["./hello", "World"]
expected = "Hello, World!"
rubric = 15

[[tests]]
name = "02"
input = ["./hello", "CS315"]
expected = "Hello, CS315!"
rubric = 15

[[tests]]
name = "03"
input = ["./argslens", "foo"]
expected = """
argv[0] = ./argslens (10)
argv[1] = foo (3)
"""
rubric = 15

[[tests]]
name = "04"
input = ["./argslens", "cs315", "computer", "architecture"]
expected = """
argv[0] = ./argslens (10)
argv[1] = cs315 (5)
argv[2] = computer (8)
argv[3] = architecture (12)
"""
rubric = 15
